version: '3.1'

services:
  database:
    image: mysql:latest
    container_name: sql_puzzle_mysqld
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      #- ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 33062:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql_puzzle
      MYSQL_USER: sql_puzzle_user
      MYSQL_PASSWORD: secret

  redis:
    container_name: sql_puzzle_redis
    image: redis:latest
